# Generated by Django 4.2.3 on 2023-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='std_class',
            field=models.CharField(max_length=20),
        ),
    ]
